/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MusicShop } from "./MusicShop";
export * as factories from "./factories";
export { MusicShop__factory } from "./factories/MusicShop__factory";
